---
- name: Exécuter un script sur un node
  hosts: node2
  become: true
  tasks:

  - name: Exécuter le script
    shell: /var/www/html/rec1.sh
    args:
      chdir: /var/www/html/
    register: script_output
