---
- name: Exécuter un script sur un node
  hosts: node2
  become: true
  tasks:

  - name: Exécuter le script
    shell: /var/www/html/rec1.sh
    args:
      chdir: /var/www/html/
<<<<<<< HEAD
    register: script_output
=======
    register: script_output
>>>>>>> 348d104cd5729b74033443437068e5d31ae61f8d
