
---
- hosts: app
  become: yes
  serial: 1

  pre_tasks:
    - name: disable the server to the haproxy
      haproxy:
        state: disabled
        host: '{{ inventory_hostname }}'
        socket: /var/lib/haproxy/stats
        backend: habackend

        delegate_to: "{{ item }}"
        with_items: "{{ groups.balancer }}"

    tasks: 
      - debug: msg="deplyment would be done here. "
      - command: /bin/false

  post_tasks:
      - name: wait for backend to come back up.
        wait_for:
          host: '{{ inventory_hostname }}'
          port: 80
          state: started
          timeout: 60

      - name: enable the backend server in haproxy
        haproxy:
          state: enabled
          host: '{{ inventory_hostname }}'
          socket: /var/lib/haproxy/stats
          backend: habackend
        delegate_to: "{{ item }}"
        with_item: "{{ groups.balancer }}"