---
- hosts: nodes
  become: true
  tasks:
  serial: 25%

    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes   
# ansible-playbook mise-a-jours --ask-become-pass