---
- hosts:
  - node1
  - node2
  become: true
  serial: 50%
  tasks:

- name: Installation de Samba sur un serveur Ubuntu
  hosts: votre_serveur

  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installation de Samba
      apt:
        name: samba
        state: present

    - name: Configuration de Samba
      lineinfile:
        path: /etc/samba/smb.conf
        regexp: '^#?\s*security\s*=\s*user'
        line: 'security = user'
        state: present
      notify:
        - Redémarrer Samba

    - name: Création d'un utilisateur Samba
      user:
        name: steph
        password: vagrant
        shell: /bin/false
        createhome: no

    - name: Redémarrage de Samba
      service:
        name: smbd
        state: restarted
