---
- name: installation de samba
  hosts: 
  - node1
  - node2
  become: true
  serial: 50%
  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installation de Samba
      apt:
        name: samba
        state: present

    - name: Configuration du service Samba
      lineinfile:
        path: /etc/samba/smb.conf
        regexp: '^#?\s*security\s*=\s*user'
        line: 'security = user'
        state: present

    - name: Création d'un utilisateur Samba
      user:
        name: steph
        password: vagrant
        shell: /bin/false
        createhome: no

    - name: Redémarrage du service Samba
      service:
        name: smbd
        state: restarted
