---
- name: Linux Reboot Demo
  hosts: 
  - node1
  - node2
  serial: 50%
  gather_facts: no
  become: true

  tasks:
    - name: Reboot the machine (Wait for 5 min)
      reboot:
        reboot_timeout: 300
