---
- name: Install VirtualBox on Ubuntu 22.04
  hosts: localhost
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add VirtualBox repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian focal contrib"
        state: present

    - name: Import Oracle public key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Install VirtualBox
      apt:
        name: virtualbox-6.1
        state: present

    - name: Start VirtualBox service
      service:
        name: virtualbox
        state: started
        enabled: true
